PayVolatilityService: 
    Db:
        LogsConnString:
            settings-key: LykkePayLogsConnString
            types: [ AzureTableStorage ]
        DataConnString: 
            settings-key: LykkePayVolatilityDataConnString
            types: [ AzureTableStorage ]
        CandlesTableName: VolatilityCandles
        VolatilityTableName: Volatility
    TickPricesSubscriber:
        ConnectionString: 
            settings-key: RabbitRawExchanges
            types: [ RabbitMq ]
        ExchangeName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-ExchangeName
        QueueName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-QueueName
    VolatilityService:
        CalculateTime: 
            settings-key: PayVolatilityService-CalculateTime
    AssetPairs: 
        settings-key: PayVolatilityService-AssetPairsWithMultiplierFactor
        types: [ JsonArray ]

AssetService:  
    ServiceUrl:
        settings-key: AssetsServiceUrl
        types: [ Tag ]        
        
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [ AzureTableStorage ]
    QueueName:
      settings-key: SlackQueueName
      types: [ AzureTableStorage ]