PayVolatilityService: 
    Db:
        LogsConnString:
            settings-key: PayVolatilityService-LogsConnString
            types: [ AzureTableStorage ]
        DataConnString: 
            settings-key: PayVolatilityService-DataConnString
            types: [ AzureTableStorage ]
        CandlesTableName: Candles
        VolatilityTableName: Volatility
    TickPricesSubscriber:
        ConnectionString: 
            settings-key: GeneralRabbitMqConnectionString
            types: [ RabbitMq ]
        ExchangeName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-ExchangeName
        QueueName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-QueueName
    VolatilityService:
        MultiplierFactor:
            settings-key: PayVolatilityService-MultiplierFactor
        CalculateTime: 
            settings-key: PayVolatilityService-CalculateTime
    AssetPairs: 
        settings-key: PayVolatilityService-AssetPairs
        types: [ JsonArray ]

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [ AzureTableStorage ]
    QueueName:
      settings-key: SlackQueueName
      types: [ AzureTableStorage ]