PayVolatilityService:
    Db:
        LogsConnString:
            settings-key: LykkePayLogsConnString
            types: [ AzureTableStorage, Tag ]
        DataConnString: 
            settings-key: LykkePayVolatilityDataConnString
            types: [ AzureTableStorage, Tag ]
        CandlesTableName: VolatilityCandles
        VolatilityTableName: Volatility
    TickPricesSubscriber:
        ConnectionString: 
            settings-key: RabbitRawExchanges
            types: [ RabbitMq, Tag ]
        ExchangeName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-ExchangeName
            types: [ Tag ]
        QueueName: 
            settings-key: PayVolatilityService-TickPriceSubscriber-QueueName
            types: [ Tag ]
    VolatilityService:
            types: [ Tag ]
        CalculateTime: 
            settings-key: PayVolatilityService-CalculateTime
            types: [ Tag ]
    AssetPairs: 
        settings-key: PayVolatilityService-AssetPairsWithMultiplierFactor
        types: [ JsonArray, Tag ]

AssetService:  
    ServiceUrl:
        settings-key: AssetsServiceUrl
        types: [ Tag ]        
        
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
        types: [ Tag ]

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types: [ AzureTableStorage ]
        QueueName:
            settings-key: SlackQueueName
            types: [ AzureTableStorage ]